fontconfig: Only apply CHERI patches for target builds
Applying these patches breaks the native build:
  In file included from ../../fontconfig-2.14.2/src/fccfg.c:27:
  ../../fontconfig-2.14.2/src/fcint.h:461:5: error: unknown type name ‘ptraddr_t’
    461 |     ptraddr_t   hash;    /* hash of key */
So for now just apply them when building for the target.

Signed-off-by: Stuart Menefy <stuart.menefy@codasip.com>