README: Improve kas and kas-container instructions
Simplify the way to use kas-container: using cheri-yocto as a container
did not work as it is missing an entrypoint script that 'kas-container'
expects. Instead the simpler direct call without custom container works
well. Remove the manual handling of SSTATE_DIR and DL_DIR. 'kas-container'
will handle these environment variables correctly and mount these
directories in the container and setup environment variables:
  podman run [...] \
      -v /mnt/build/yocto/downloads:/downloads:rw \
      -e DL_DIR=/downloads \
      -v /mnt/build/yocto/sstate:/sstate:rw \
      -e SSTATE_DIR=/sstate [...]

Simplify paths: './' is not required for the path to the kas yml file.

'pip install' will in most setups result in an error message
  error: externally-managed-environment
To avoid that, recommend the use of pipx which installs and runs the
tools in isolated environments.

Fixup headers to have a consistent header structure. 'meta-cheri' is
level 1, the others level 2 and lower.

Signed-off-by: Markus Schneider-Pargmann (The Capable Hub) <msp@baylibre.com>